/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const CategoryId = IDL.Text;
export const FoodItemId = IDL.Text;
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const FoodItem = IDL.Record({
  'id' : FoodItemId,
  'hot' : IDL.Bool,
  'categoryId' : CategoryId,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'enabled' : IDL.Bool,
  'image' : IDL.Opt(ExternalBlob),
  'price' : IDL.Float64,
});
export const AnalyticsData = IDL.Record({
  'activeItems' : IDL.Nat,
  'totalCategories' : IDL.Nat,
  'totalItems' : IDL.Nat,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Opt(IDL.Text),
});
export const Category = IDL.Record({
  'id' : CategoryId,
  'order' : IDL.Nat,
  'name' : IDL.Text,
  'enabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addCategory' : IDL.Func([IDL.Text, IDL.Nat], [CategoryId], []),
  'addFoodItem' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Float64, IDL.Bool, CategoryId, IDL.Nat],
      [FoodItemId],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteCategory' : IDL.Func([CategoryId], [], []),
  'deleteFoodItem' : IDL.Func([FoodItemId], [], []),
  'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
  'getAnalytics' : IDL.Func([], [AnalyticsData], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
  'getFoodItemsForCategory' : IDL.Func(
      [CategoryId],
      [IDL.Vec(FoodItem)],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'reorderCategories' : IDL.Func([IDL.Vec(CategoryId)], [], []),
  'reorderFoodItems' : IDL.Func([IDL.Vec(FoodItemId)], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'toggleCategoryEnabled' : IDL.Func([CategoryId, IDL.Bool], [], []),
  'toggleFoodItemEnabled' : IDL.Func([FoodItemId, IDL.Bool], [], []),
  'updateCategory' : IDL.Func([CategoryId, IDL.Text], [], []),
  'updateFoodItem' : IDL.Func(
      [FoodItemId, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool, CategoryId],
      [],
      [],
    ),
  'updateFoodItemImage' : IDL.Func([FoodItemId, IDL.Opt(ExternalBlob)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const CategoryId = IDL.Text;
  const FoodItemId = IDL.Text;
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const FoodItem = IDL.Record({
    'id' : FoodItemId,
    'hot' : IDL.Bool,
    'categoryId' : CategoryId,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'enabled' : IDL.Bool,
    'image' : IDL.Opt(ExternalBlob),
    'price' : IDL.Float64,
  });
  const AnalyticsData = IDL.Record({
    'activeItems' : IDL.Nat,
    'totalCategories' : IDL.Nat,
    'totalItems' : IDL.Nat,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Opt(IDL.Text),
  });
  const Category = IDL.Record({
    'id' : CategoryId,
    'order' : IDL.Nat,
    'name' : IDL.Text,
    'enabled' : IDL.Bool,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addCategory' : IDL.Func([IDL.Text, IDL.Nat], [CategoryId], []),
    'addFoodItem' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Float64, IDL.Bool, CategoryId, IDL.Nat],
        [FoodItemId],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteCategory' : IDL.Func([CategoryId], [], []),
    'deleteFoodItem' : IDL.Func([FoodItemId], [], []),
    'getAllFoodItems' : IDL.Func([], [IDL.Vec(FoodItem)], ['query']),
    'getAnalytics' : IDL.Func([], [AnalyticsData], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCategories' : IDL.Func([], [IDL.Vec(Category)], ['query']),
    'getFoodItemsForCategory' : IDL.Func(
        [CategoryId],
        [IDL.Vec(FoodItem)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'reorderCategories' : IDL.Func([IDL.Vec(CategoryId)], [], []),
    'reorderFoodItems' : IDL.Func([IDL.Vec(FoodItemId)], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'toggleCategoryEnabled' : IDL.Func([CategoryId, IDL.Bool], [], []),
    'toggleFoodItemEnabled' : IDL.Func([FoodItemId, IDL.Bool], [], []),
    'updateCategory' : IDL.Func([CategoryId, IDL.Text], [], []),
    'updateFoodItem' : IDL.Func(
        [FoodItemId, IDL.Text, IDL.Text, IDL.Float64, IDL.Bool, CategoryId],
        [],
        [],
      ),
    'updateFoodItemImage' : IDL.Func(
        [FoodItemId, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };