/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnalyticsData {
  'activeItems' : bigint,
  'totalCategories' : bigint,
  'totalItems' : bigint,
}
export interface Category {
  'id' : CategoryId,
  'order' : bigint,
  'name' : string,
  'enabled' : boolean,
}
export type CategoryId = string;
export type ExternalBlob = Uint8Array;
export interface FoodItem {
  'id' : FoodItemId,
  'hot' : boolean,
  'categoryId' : CategoryId,
  'order' : bigint,
  'name' : string,
  'description' : string,
  'enabled' : boolean,
  'image' : [] | [ExternalBlob],
  'price' : number,
}
export type FoodItemId = string;
export interface UserProfile { 'name' : string, 'email' : [] | [string] }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addCategory' : ActorMethod<[string, bigint], CategoryId>,
  'addFoodItem' : ActorMethod<
    [string, string, number, boolean, CategoryId, bigint],
    FoodItemId
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteCategory' : ActorMethod<[CategoryId], undefined>,
  'deleteFoodItem' : ActorMethod<[FoodItemId], undefined>,
  'getAllFoodItems' : ActorMethod<[], Array<FoodItem>>,
  'getAnalytics' : ActorMethod<[], AnalyticsData>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCategories' : ActorMethod<[], Array<Category>>,
  'getFoodItemsForCategory' : ActorMethod<[CategoryId], Array<FoodItem>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'reorderCategories' : ActorMethod<[Array<CategoryId>], undefined>,
  'reorderFoodItems' : ActorMethod<[Array<FoodItemId>], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'toggleCategoryEnabled' : ActorMethod<[CategoryId, boolean], undefined>,
  'toggleFoodItemEnabled' : ActorMethod<[FoodItemId, boolean], undefined>,
  'updateCategory' : ActorMethod<[CategoryId, string], undefined>,
  'updateFoodItem' : ActorMethod<
    [FoodItemId, string, string, number, boolean, CategoryId],
    undefined
  >,
  'updateFoodItemImage' : ActorMethod<
    [FoodItemId, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];